//Eventos de proyecto
export const FORMULARIO_PROYECTO = "FORMULARIO_PROYECTO";
export const MOSTRAR_PROYECTOS = "MOSTRAR_PROYECTOS";
export const NUEVO_PROYECTO = "NUEVO_PROYECTO";
export const MOSTRAR_ERROR_FORMULARIO_PROYECTO =
  "MOSTRAR_ERROR_FORMULARIO_PROYECTO";
export const OCULTAR_ERROR_FORMULARIO_PROYECTO =
  "OCULTAR_ERROR_FORMULARIO_PROYECTO";
export const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";
export const PROYECTO_ERROR = "PROYECTO_ERROR";
export const LIMPIAR_PROYECTOS = "LIMPIAR_PROYECTOS";

//Eventos de tareas
export const MOSTRAR_TAREAS = "MOSTRAR_TAREAS";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const MOSTRAR_ERROR_FORMULARIO_TAREA = "MOSTRAR_ERROR_FORMULARIO_TAREA";
export const OCULTAR_ERROR_FORMULARIO_TAREA = "OCULTAR_ERROR_FORMULARIO_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const ESTADO_TAREA = "ESTADO_TAREA";
export const TAREA_ACTUAL = "TAREA_ACTUAL";
export const ACTUALIZAR_TAREA = "ACTUALIZAR_TAREA";
export const LIMPIAR_TAREAS = "LIMPIAR_TAREAS";

//Eventos alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

//Eventos autenticacion con la API
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
